development:
  adapter: postgresql
  encoding: unicode
  database: refactortv_development
  host: localhost
  pool: 5
  username: refactortv
  password:
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: refactortv_test
  host: localhost
  pool: 5
  username: refactortv
  password:
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: refactortv_production
  host: localhost
  pool: 5
  username: refactortv
  password:
  min_messages: WARNING
